load("@rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_to_json_test")

jsonnet_to_json_test(
    name = "test1",
    src = "test1.jsonnet",
    golden = "test1_golden.json",
    deps = ["//path-utils:main"],
    timeout = "short",
)

jsonnet_to_json_test(
    name = "test2",
    src = "test2.jsonnet",
    golden = "test2_golden.json",
    deps = ["//path-utils:main"],
    timeout = "short",
)

jsonnet_to_json_test(
    name = "test3",
    src = "test3.jsonnet",
    golden = "test3_golden.json",
    deps = ["//path-utils:main"],
    timeout = "short",
)

jsonnet_to_json_test(
    name = "test4",
    src = "test4.jsonnet",
    golden = "test4_golden.json",
    deps = ["//path-utils:main"],
    timeout = "short",
)

jsonnet_to_json_test(
    name = "test5",
    src = "test5.jsonnet",
    golden = "test5_golden.json",
    deps = ["//path-utils:main"],
    timeout = "short",
)

jsonnet_to_json_test(
    name = "test6",
    src = "test6.jsonnet",
    golden = "test6_golden.json",
    deps = ["//path-utils:main"],
    timeout = "short",
)

jsonnet_to_json_test(
    name = "test7",
    src = "test7.jsonnet",
    golden = "test7_golden.json",
    deps = ["//path-utils:main"],
    timeout = "short",
)
